plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'io.github.m1jawa.mcmodsmanager.cli.ModsManagerCommand' 
}

group = 'io.github.m1jawa'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'info.picocli:picocli:4.7.7'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}