plugins {
    id 'java'
    id 'application'
    id 'org.graalvm.buildtools.native' version '0.10.1'
    id 'com.gradleup.shadow' version '8.3.5'
}

application {
    mainClass = 'io.github.m1jawa.mcmodsmanager.cli.ModsManagerCommand' 
}

group = 'io.github.m1jawa'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'info.picocli:picocli:4.7.7'
    annotationProcessor 'info.picocli:picocli-codegen:4.7.6'
}

java { 
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}